ADMINS=max.bieder@mann.com,
SECRET_KEY=admins-secret-key

FLASK_APP=purchase_tracer.py
FLASK_DEBUG=1
FLASK_ENV=development
FLASK_RUN_PORT=8000

MAIL_SERVER=localhost
MAIL_PORT=8025
# MAIL_USE_TLS=1
# MAIL_USERNAME=
# MAIL_PASSWORD=
# MAIL_DEBUG=app.debug
# MAIL_USE_SSL=0
# MAIL_DEFAULT_SENDER=
# MAIL_MAX_EMAILS=
# MAIL_SUPPRESS_SEND=app.testing
# MAIL_ASCII_ATTACHMENTS=0

ELEMENTS_PER_PAGE =25

LANGUAGES=en,de,nl,th

GOOGLE_TRANSLATOR_KEY=OPEN_SOURCE
