"""add purchase_date and purchaser to Purchase

Revision ID: 67c8e28c9070
Revises: 2f43aefa2f20
Create Date: 2019-02-26 16:35:18.632750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67c8e28c9070'
down_revision = '2f43aefa2f20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase', sa.Column('purchase_date', sa.DateTime(), nullable=True))
    op.add_column('purchase', sa.Column('purchaser', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchase', 'purchaser')
    op.drop_column('purchase', 'purchase_date')
    # ### end Alembic commands ###
